config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'product_groups#index'
  
  devise_for :users , path: '', 
  path_names: {
   sign_in: 'login', 
   sign_out: 'logout', 
   sign_up: 'register'
  }, 
  controllers: { 
    registrations: 'registrations' 
  }
  devise_scope :user do
    get '/confirmation-getting-started' => 'registrations#getting_started', as: 'confirmation_getting_started'
  end
  
  get 'contact', to: 'contact#index'

  resources :products
  get "/fetch_products" => 'products#from_category', as: 'fetch_products'
  resources :product_groups
  
  resources :cart_items
  resources :orders do
    get 'finished_order', to: 'orders#finished_order'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
has_many :cart_items, dependent: :destroy

  def total_price
    cart_items.to_a.sum { |item| item.total_price }
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  enum status: [:received, :completed]

  def create_order

  end

  def total_price
    price = order_items.to_a.sum { |item| item.total_price }
    price *= 0.5 if is_discount
  end    
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  def total_price
    price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_group
  has_many :cart_items
  has_many :order_items
end

app/models/product_group.rb
class ProductGroup < ApplicationRecord
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
  include DeviseWhitelist
  
  before_action :current_cart
  
  def current_cart
    begin
      @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end

    @cart
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end
  
  def create
    order = params[:order]
    new_order = Order.new(order_params)
    # new_order.total_price = current_cart.total_price
    new_order.status = 0 # 0 is 
    # byebug
    new_order.is_discount = true if order[:discount_code] == "CODERSCHOOL"

    if new_order.save
      current_cart.cart_items.each do |item|
        new_order.order_items.create(product_id: item.product_id, quantity: item.quantity, price: item.price)
      end

      current_cart.destroy
      

      redirect_to order_finished_order_path(new_order.id)
    else
      redirect_to new_order
    end
  end
  
  def finished_order
    @order = Order.find(params[:order_id])
    @mail_status = true
    # byebug
    begin
    OrderMailer.finished_order_email(@order).deliver_now
    rescue StandardError
      @mail_status = false
    end
  end

  private
    def order_params
      params.require(:order).permit(:customer_name, :email, :phone, :address, :discount_code, :is_discount)
    end
end

app/controllers/product_groups_controller.rb
class ProductGroupsController < ApplicationController
    def index
        @pgroups = ProductGroup.all
    end
    
    def show
        @pgroup = ProductGroup.find(params[:id])
    
        respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @pgroup}
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @pgroups = ProductGroup.all
  end
  def from_category
    @selected = Product.where(:product_group_id => params[:product_group_id])
    respond_to do |format|
      format.js
    end
  end

  def show
    # current_cart
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
   base_title = "Urban Store"
   if page_title.empty?
     base_title
   else
     "#{page_title} | #{base_title}"
   end
  end

   def is_active(test_path)
     'active' if current_page?(test_path)
   end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_groups_helper.rb
module ProductGroupsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/contact/index.html.erb
<% provide(:title, "Contact Us") %>
<div class="contact">
  <div class="container">
      <h2 class="tittle">How To Find Us</h2>
      <div class="contact-bottom">
          <iframe src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJZ-RLqJYvdTER5NKhwRjE3pU&key=AIzaSyDC_qSYehzgYnTRr3mxMAz5k9Un3rlJ8JQ" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
      <div class="row">
        <div class="col-md-4 contact-left">
            <h4>Show Room</h4>
            <h5>
                <i class="fa fa-magnet" aria-hidden="true"></i> URBAN STORE
            </h5>
            <ul>
              <p><i class="fa fa-map-marker" aria-hidden="true"></i> CENTER PHU MY HUNG</p>
              <li>S8-1 Sky Garden 1 (đường Nguyễn Văn Linh), Phú Mỹ Hưng, Quận 7, TP. HCM, Việt Nam.</li>
              <li>Tel: (84-8) 3925.2980 - Hotline: 090909.4641</li>
            </ul>
        </div>
        <div class="col-md-8 contact-left cont">
            <h4>Contact Form</h4>
            <p>Need to ask about the product, Email right now to us: </p>
            <form action="#" method="post">
                <input type="ttext" name="Name" value="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}" required="">
                <input type="email" name="Email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
                <input type="ttext" name="Phone" value="Phone" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Phone';}" required="">
                <textarea type="text" name="Message" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message...';}" required>Message...</textarea>
                <input type="reset" value="Submit">
            </form>
        </div>
        <!--<div class="clearfix"></div>-->
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="MainWrapper">

      <!--Header-->
      <header>
        <div class="container">
          <div class="header-top">
            <div class="container">
              <div class="top-left"><a href="#"> <i class="fa fa-phone" aria-hidden="true"></i> (+84)1676-825-746 </a> &thinsp; <a href="#"> <i class="fa fa-envelope" aria-hidden="true"></i> jient.contact@gmail.com</a></div>
                <div class="top-right">
                	<ul>
                	  <% if current_user %>
                	    <%= link_to rails_admin_path do%>
                        <%= current_user.firstname %>
                      <% end if current_user.admin == true %>
                	    <%= link_to edit_user_registration_path do%>
                        <%= current_user.firstname %>
                      <% end if current_user.admin == false %>
                      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
                    <% else %>
                      <%= link_to 'Register', new_user_registration_path %>
                      <%= link_to 'Login',new_user_session_path %>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header
      <!--endHeader-->
      <!--Banner-->
      <div class="container" style="margin-bottom: 0; padding-bottom: 0;">
        <nav class="navbar sticky-top navbar-expand-lg navbar-dark ">
          <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <%= link_to product_groups_path, class: 'navbar-brand' do %>
              <%= image_tag("logo-white.png") %>
            <% end%>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="nav navbar-nav mr-auto">
                <li class="nav-item <%= is_active(products_path) %>">
                  <%= link_to "STORE", products_path, class: 'nav-link' %>
                </li>
                <li class="nav-item <%= is_active(contact_path) %>">
                    <%= link_to "CONTACT", contact_path, class: 'nav-link' %>
                </li>
              </ul>
              <ul class="nav navbar-nav pull-right">
                <li class="nav-item dropdown">
                  <a class="dropdown-toggle nav-link" data-toggle="dropdown" href="#" aria-expanded="true">
                    <i class="fa fa-shopping-cart fa-lg" style="color: #fff;"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right">
                    <% @cart.cart_items.each do |item| %>
                      <%= link_to "#{item.product.p_name} x #{item.quantity}", product_path(item.product.id), class: 'dropdown-item' %>
                    <% end %>
                    <div class="dropdown-divider" href="#" ></div>
                    <%= link_to new_order_path, class:'dropdown-item' do %>
                      <i class="fa fa-check" aria-hidden="true" ></i> CHECK OUT
                    <% end%>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div style="background-color: #000;">
          <p class=" notice" style="color: #ffffff;"><%= notice %></p>
          <p class=" alert" style="color: #ffffff;"><%= alert %></p>
        </div>
      </div>
      <!--EndBanner-->
      <!--Content-->
      <div id="content" class="container" >
        <%= yield %>
      </div>
      <!--EndContent-->
      <!--Footer-->
      <div class="container">
        <footer>
            <div class="row">
              <div class="container">
                <h1><%= image_tag("logo.png") %></h1>
                <hr>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 center-right">
                <p class="centertitle">CENTER PHU MY HUNG </p>
                <ul>
                  <li>S8-1 Sky Garden 1 (đường Nguyễn Văn Linh), Phú Mỹ Hưng, Quận 7, TP. HCM, Việt Nam.</li>
                  <li>Tel: (84-8) 3925.2980 - Hotline: 090909.4641</li>
                </ul>
              </div>
            </div>
            <div class="copy-section">
                <div class="container">
                    <div class="footer-top">
                        <p>Copyright &copy; 2018 URBAN STORE. All rights reserved | Powered and Designed by JientDoNgoc</p>
                    </div>
                    <div class="social-icons">
                        <a href="https://www.facebook.com/maccenter.vn/"><i class="icon"></i></a>
                        <a href="#"><i class="icon1"></i></a>
                        <a href="#"><i class="icon2"></i></a>
                        <a href="#"><i class="icon3"></i></a>
                    </div>
                </div>
            </div>
        </footer>
      </div>
      <!--EndFooter-->
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/product_groups/index.html.erb
<% provide(:title, "Home") %>
<div class="home">
  <div class="container">
    <div class="row">
      <% @pgroups.each do |pgroup| %>
          <div class="col-sm-6 col-md-4 col-lg-4 mt-4">
              <div class="card">
                <%= link_to product_group_path(pgroup.id) do%>
                  <img class="card-img-top" src="<%= pgroup.pg_img %>">
                <% end %>
                  <div class="card-block">
                    <%= hidden_field_tag 'pg_id', pgroup.id %>
                    <%= link_to product_group_path(pgroup.id) do%>
                      <h5 class="card-title"><%= pgroup.pg_name %></h5>
                    <% end %>
                  </div>
              </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/product_groups/show.html.erb
<% provide(:title, "Products") %>
<div class="products">
  <div class="container">
    <div class="row">
      <% @pgroup.products.each do |product| %>
          <div class="col-sm-6 col-md-4 col-lg-4 mt-4">
            <div class="card">
              <%= link_to product_path(product.id) do%>
                <div class="img-box">
                  <img class="card-img-top" src="<%= product.p_img %>">
                </div>
              <% end %>
              <div class="card-block">
                <%= hidden_field_tag 'p_id', product.id %>
                <div class="details">
                  <%= link_to product_path(product.id) do%>
                    <h5 class="card-title"><%= product.p_name %></h5>
                  <% end %>
                  <p><%= simple_format product.overview%></p>
                </div>
                <p class="price"><%= number_to_currency (product.price), unit: 'VND ', precision: 0  %><p>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>